service: ${env:APP}
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

provider:
  name: google
  runtime: nodejs18
  region: us-central1
  project: ${env:PROJECT_ID}
  credentials: ${env:GCLOUD_CREDENTIALS}
  environment:
    APP: ${env:APP}
    BUCKET: ${env:BUCKET}
    FIRESTORE_COLLECTION: ${env:FIRESTORE_COLLECTION}
    GCLOUD_SERVICE_ACCOUNT_EMAIL: ${env:GCLOUD_SERVICE_ACCOUNT_EMAIL}
    GCLOUD_TASKS_QUEUE: ${env:GCLOUD_TASKS_QUEUE}
    PROJECT_ID: ${self:provider.project}
    REGION: ${self:provider.region}
    SENTRY_DSN: ${env:SENTRY_DSN}
    STAGE: ${opt:stage}

# Include only the built code
package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  # Event-triggered function. Limits are provided for safety.
  # The resource bucket must be already created.
  process_file:
    handler: processFile
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/${self:provider.project}/buckets/${env:BUCKET}

  # HTTP request-triggered function
  parse_metadata:
    handler: parseMetadata
    events:
      - http: parse_metadata
